name: Format

on: [ push, pull_request ]

jobs:

  formatting:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@fe78db8a90171b6a836449f8d0e982d5d71e5c5a # v3.6.0
        with:
          args: "--aosp --replace"
          skipCommit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code
